name: CI (Node)

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.js"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/**"
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Lint (optional)
        run: npm run lint --if-present

      - name: Test (optional)
        run: npm test --if-present

      - name: Build (optional)
        run: npm run build --if-present

      - name: App starts?
        run: |
          nohup npm start &>/dev/null &
          sleep 2
          curl -sSf http://localhost:3000/health
